
####################################################################################
# Generated by Vivado 2025.2 built on 'Fri Nov 14 19:35:11 GMT 2025' by 'xbuild'
# Command Used: write_xdc -force V://_synth_bc/acc36_realrom_200_member_b_pipeline0000926_ascii_ramdecomp/reports/constraints_restored.xdc
####################################################################################


####################################################################################
# Constraints from file : 'c_top.xdc'
####################################################################################

##############################################################################
# c_top.xdc —— C 侧 RTL 骨架顶层约束（ACX750-200T）
#-----------------------------------------------------------------------------
# 依据：任务书 v3.2.2 §五.4（时钟与复位，已冻结）/ §五.5（XDC 基线与引脚）
# 复用：bench/onboard_dual_int8/constr/top_onboard.xdc（**已上板实测可用**）
#
# 目标器件：xc7a200tfbg484-2（Artix-7 XC7A200T，DSP48E1，Vivado 2022.2）
#
# 适用顶层：c_top / c_synth_top（端口同名）
#   sys_clk / rst_n / led[7:0] / uart_tx
##############################################################################

#-----------------------------------------------------------------------------
# 时钟：板载 50MHz 有源晶振
#   必须加 create_clock，否则 MMCM 无法正确计算倍频比，实现会报错
#   MMCM 输出 200MHz 由工具自动推导，无需手动 create_generated_clock
#-----------------------------------------------------------------------------
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports sys_clk]
create_clock -period 20.000 -name sys_clk [get_ports sys_clk]

#-----------------------------------------------------------------------------
# 复位按键 S0（按下为低电平）
#   按键是**异步输入**，必须做假路径；不得直接当同步复位使用
#   RTL 侧复位汇聚为 sys_rst_n = rst_n & mmcm_locked
#-----------------------------------------------------------------------------
set_property -dict {PACKAGE_PIN D21 IOSTANDARD LVCMOS33} [get_ports rst_n]
set_false_path -from [get_ports rst_n]

#-----------------------------------------------------------------------------
# LED0..LED7
#   LED 映射（见 rtl/c_top.v）：
#     [0] busy      [1] done(锁存)   [2] 心跳        [3] 协议错(锁存)
#     [4] 溢出错    [5][6] buf_state [7] 有回读活动
#-----------------------------------------------------------------------------
set_property -dict {PACKAGE_PIN U22 IOSTANDARD LVCMOS33} [get_ports {led[0]}]
set_property -dict {PACKAGE_PIN V22 IOSTANDARD LVCMOS33} [get_ports {led[1]}]
set_property -dict {PACKAGE_PIN W21 IOSTANDARD LVCMOS33} [get_ports {led[2]}]
set_property -dict {PACKAGE_PIN W22 IOSTANDARD LVCMOS33} [get_ports {led[3]}]
set_property -dict {PACKAGE_PIN Y21 IOSTANDARD LVCMOS33} [get_ports {led[4]}]
set_property -dict {PACKAGE_PIN Y22 IOSTANDARD LVCMOS33} [get_ports {led[5]}]
set_property -dict {PACKAGE_PIN N13 IOSTANDARD LVCMOS33} [get_ports {led[6]}]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports {led[7]}]

#-----------------------------------------------------------------------------
# UART TX（CH9102）
#
# TODO(UART_PIN_CONFIRM): FPGA 侧管脚**尚未确认**（v3.2.2 §五.5：
#   「CH9102 芯片在位，但 FPGA 侧管脚需在首次串口联通时用 IO Planner 确认」；
#   §8.4 任务⑥）。
#   ⇒ 本行**保持注释**，首次串口联通、确认管脚后再打开。
#   ⇒ 综合/实现取证可以运行，但 UART 引脚未约束意味着尚不能据此交付板级 bitstream。
#
# 确认后请按下面形式补全（示例，管脚号待填）：
#   set_property -dict {PACKAGE_PIN XX  IOSTANDARD LVCMOS33} [get_ports uart_tx]
#-----------------------------------------------------------------------------

#-----------------------------------------------------------------------------
# 配置与容错（**基线 XDC 已含，勿删**）
#-----------------------------------------------------------------------------
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

# 未使用的引脚不报错（板上有大量外设只接了部分引脚）


# User Generated miscellaneous constraints 

set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/issue_phase[0]}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[0]_rep_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[0]_rep__0_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[0]_rep__1_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[0]_rep__10_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[0]_rep__11_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[0]_rep__13_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[0]_rep__14_1}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[0]_rep__15_1}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[0]_rep__16_1}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[0]_rep__2_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[0]_rep__3_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[0]_rep__4_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[0]_rep__5_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[0]_rep__6_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[0]_rep__7_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[0]_rep__8_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[0]_rep__9_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[1]_rep_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[1]_rep__0_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[1]_rep__1_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[1]_rep__10_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[1]_rep__11_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[1]_rep__12_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[1]_rep__13_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[1]_rep__14_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[1]_rep__15_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[1]_rep__16_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[1]_rep__2_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[1]_rep__3_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[1]_rep__4_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[1]_rep__5_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[1]_rep__6_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[1]_rep__7_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[1]_rep__8_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[1]_rep__9_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/issue_phase[2]}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[2]_rep_1}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[2]_rep__0_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[2]_rep__1_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[2]_rep__2_2}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[2]_rep__3_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[2]_rep__4_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[2]_rep__5_2}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[2]_rep__6_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[2]_rep__7_n_0}]
set_property MAX_FANOUT 48 [get_nets {u_top/u_core/u_b/u_b_core/core/core/l5/mac/issue/out_phase_reg[2]_rep__8_n_0}]

# User Generated XDC timing constraints 

set_clock_uncertainty -setup -from [get_clocks -quiet -of_objects [get_pins -quiet u_top/g_mmcm.u_mmcm/CLKOUT0]] -to [get_clocks -quiet -of_objects [get_pins -quiet u_top/g_mmcm.u_mmcm/CLKOUT0]] 0.000
set_clock_uncertainty -setup -from [get_clocks -quiet -of_objects [get_pins -quiet u_top/g_mmcm.u_mmcm/CLKOUT0]] -to [get_clocks -quiet -of_objects [get_pins -quiet u_top/g_mmcm.u_mmcm/CLKOUT0]] 0.000

# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
