
####################################################################################
# Generated by Vivado 2025.2 built on 'Fri Nov 14 19:35:11 GMT 2025' by 'xbuild'
# Command Used: write_xdc synthesized_constraints.xdc
####################################################################################


####################################################################################
# Constraints from file : 'pins_clocks_internal_only.xdc'
####################################################################################

# INTERNAL EXPERIMENT: external DDR min/max omitted, cannot release BIT.
set_property PACKAGE_PIN W19 [get_ports sys_clk50]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk50]
set_property PACKAGE_PIN D21 [get_ports reset_n]
set_property IOSTANDARD LVCMOS33 [get_ports reset_n]
set_property PACKAGE_PIN Y18 [get_ports rgmii_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_rxc]
set_property PACKAGE_PIN T20 [get_ports rgmii_rxctl]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_rxctl]
set_property PACKAGE_PIN AB21 [get_ports rgmii_txc]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_txc]
set_property PACKAGE_PIN AA19 [get_ports rgmii_txctl]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_txctl]
set_property PACKAGE_PIN P14 [get_ports phy_reset_n]
set_property IOSTANDARD LVCMOS33 [get_ports phy_reset_n]
set_property PACKAGE_PIN P20 [get_ports {rgmii_rxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[0]}]
set_property PACKAGE_PIN N15 [get_ports {rgmii_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[1]}]
set_property PACKAGE_PIN AA18 [get_ports {rgmii_rxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[2]}]
set_property PACKAGE_PIN AB18 [get_ports {rgmii_rxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[3]}]
set_property PACKAGE_PIN AB20 [get_ports {rgmii_txd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[0]}]
set_property PACKAGE_PIN Y19 [get_ports {rgmii_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[1]}]
set_property PACKAGE_PIN AB22 [get_ports {rgmii_txd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[2]}]
set_property PACKAGE_PIN W20 [get_ports {rgmii_txd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[3]}]
set_property PACKAGE_PIN U22 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN V22 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN W21 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN W22 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN Y21 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN Y22 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN N13 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN N17 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
create_clock -period 20.000 -name sys50 [get_ports sys_clk50]
create_clock -period 7.200 -name phy_rx125 -waveform {0.000 3.240} [get_ports rgmii_rxc]
set_false_path -from [get_ports reset_n]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports mdc]
set_property -dict {PACKAGE_PIN U21 IOSTANDARD LVCMOS33} [get_ports mdio]
set_property -dict {PACKAGE_PIN M21 IOSTANDARD LVCMOS33} [get_ports uart_tx]
set_property -dict {SLEW SLOW DRIVE 4} [get_ports {mdc mdio}]
set_property PULLTYPE PULLUP [get_ports mdio]


####################################################################################
# Constraints from file : 'xpm_cdc_gray.tcl'
####################################################################################

# Scoped constraints for xpm_cdc_gray




current_instance u_video/u_rx_bridge/u_data/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_max_delay -datapath_only -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.667
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.667

create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -tags "1009444" -scope -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Fri Oct  9 12:01:12 GMT 2026"


# Scoped constraints for xpm_cdc_gray




current_instance -quiet
current_instance u_video/u_rx_bridge/u_data/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_max_delay -datapath_only -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 7.200
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.667

create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -tags "1009444" -scope -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Fri Oct  9 12:01:12 GMT 2026"


# Scoped constraints for xpm_cdc_gray




current_instance -quiet
current_instance u_video/u_tx_bridge/u_data/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_max_delay -datapath_only -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 8.000
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.667

create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -tags "1009444" -scope -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Fri Oct  9 12:01:12 GMT 2026"


# Scoped constraints for xpm_cdc_gray




current_instance -quiet
current_instance u_video/u_tx_bridge/u_data/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_max_delay -datapath_only -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.667
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.667

create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -tags "1009444" -scope -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Fri Oct  9 12:01:12 GMT 2026"


# Scoped constraints for xpm_cdc_gray




current_instance -quiet
current_instance u_video/u_rx_bridge/u_data/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_max_delay -datapath_only -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 7.200
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.667

create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -tags "1009444" -scope -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Fri Oct  9 12:01:12 GMT 2026"


# Scoped constraints for xpm_cdc_gray




current_instance -quiet
current_instance u_video/u_tx_bridge/u_data/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_max_delay -datapath_only -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.667
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.667

create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -tags "1009444" -scope -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Fri Oct  9 12:01:12 GMT 2026"


# Scoped constraints for xpm_cdc_gray




current_instance -quiet
current_instance u_video/u_rx_bridge/u_data/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_max_delay -datapath_only -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.667
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.667

create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -tags "1009444" -scope -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Fri Oct  9 12:01:12 GMT 2026"


# Scoped constraints for xpm_cdc_gray




current_instance -quiet
current_instance u_video/u_tx_bridge/u_data/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_max_delay -datapath_only -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 8.000
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.667

create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -tags "1009444" -scope -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Fri Oct  9 12:01:12 GMT 2026"


# Scoped constraints for xpm_cdc_gray




current_instance -quiet
current_instance u_video/u_rx_bridge/u_metadata/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_max_delay -datapath_only -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.667
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.667

create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -tags "1009444" -scope -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Fri Oct  9 12:01:12 GMT 2026"


# Scoped constraints for xpm_cdc_gray




current_instance -quiet
current_instance u_video/u_rx_bridge/u_metadata/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_max_delay -datapath_only -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 7.200
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.667

create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -tags "1009444" -scope -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Fri Oct  9 12:01:12 GMT 2026"


# Scoped constraints for xpm_cdc_gray




current_instance -quiet
current_instance u_video/u_tx_bridge/u_metadata/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_max_delay -datapath_only -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 8.000
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.667

create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -tags "1009444" -scope -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Fri Oct  9 12:01:12 GMT 2026"


# Scoped constraints for xpm_cdc_gray




current_instance -quiet
current_instance u_video/u_tx_bridge/u_metadata/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_max_delay -datapath_only -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.667
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.667

create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -tags "1009444" -scope -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Fri Oct  9 12:01:12 GMT 2026"


# Scoped constraints for xpm_cdc_gray




current_instance -quiet
current_instance u_video/u_rx_bridge/u_metadata/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_max_delay -datapath_only -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 7.200
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.667

create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -tags "1009444" -scope -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Fri Oct  9 12:01:12 GMT 2026"


# Scoped constraints for xpm_cdc_gray




current_instance -quiet
current_instance u_video/u_tx_bridge/u_metadata/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_max_delay -datapath_only -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.667
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.667

create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -tags "1009444" -scope -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Fri Oct  9 12:01:12 GMT 2026"


# Scoped constraints for xpm_cdc_gray




current_instance -quiet
current_instance u_video/u_rx_bridge/u_metadata/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_max_delay -datapath_only -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.667
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.667

create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -tags "1009444" -scope -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Fri Oct  9 12:01:12 GMT 2026"


# Scoped constraints for xpm_cdc_gray




current_instance -quiet
current_instance u_video/u_tx_bridge/u_metadata/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_max_delay -datapath_only -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 8.000
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 6.667

create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -tags "1009444" -scope -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Fri Oct  9 12:01:12 GMT 2026"



####################################################################################
# Constraints from file : 'xpm_cdc_sync_rst.tcl'
####################################################################################

# Scoped constraints for xpm_cdc_srst
current_instance -quiet
current_instance u_video/u_rx_bridge/u_data/gnuram_async_fifo.xpm_fifo_base_inst/xpm_fifo_rst_inst/gen_rst_ic.rrst_wr_inst
set_false_path -to [get_cells {syncstages_ff_reg[0]}]


# Scoped constraints for xpm_cdc_srst
current_instance -quiet
current_instance u_video/u_rx_bridge/u_data/gnuram_async_fifo.xpm_fifo_base_inst/xpm_fifo_rst_inst/gen_rst_ic.wrst_rd_inst
set_false_path -to [get_cells {syncstages_ff_reg[0]}]


# Scoped constraints for xpm_cdc_srst
current_instance -quiet
current_instance u_video/u_rx_bridge/u_metadata/gnuram_async_fifo.xpm_fifo_base_inst/xpm_fifo_rst_inst/gen_rst_ic.rrst_wr_inst
set_false_path -to [get_cells {syncstages_ff_reg[0]}]


# Scoped constraints for xpm_cdc_srst
current_instance -quiet
current_instance u_video/u_rx_bridge/u_metadata/gnuram_async_fifo.xpm_fifo_base_inst/xpm_fifo_rst_inst/gen_rst_ic.wrst_rd_inst
set_false_path -to [get_cells {syncstages_ff_reg[0]}]


# Scoped constraints for xpm_cdc_srst
current_instance -quiet
current_instance u_video/u_tx_bridge/u_metadata/gnuram_async_fifo.xpm_fifo_base_inst/xpm_fifo_rst_inst/gen_rst_ic.rrst_wr_inst
set_false_path -to [get_cells {syncstages_ff_reg[0]}]


# Scoped constraints for xpm_cdc_srst
current_instance -quiet
current_instance u_video/u_tx_bridge/u_metadata/gnuram_async_fifo.xpm_fifo_base_inst/xpm_fifo_rst_inst/gen_rst_ic.wrst_rd_inst
set_false_path -to [get_cells {syncstages_ff_reg[0]}]


# Scoped constraints for xpm_cdc_srst
current_instance -quiet
current_instance u_video/u_tx_bridge/u_data/gnuram_async_fifo.xpm_fifo_base_inst/xpm_fifo_rst_inst/gen_rst_ic.rrst_wr_inst
set_false_path -to [get_cells {syncstages_ff_reg[0]}]


# Scoped constraints for xpm_cdc_srst
current_instance -quiet
current_instance u_video/u_tx_bridge/u_data/gnuram_async_fifo.xpm_fifo_base_inst/xpm_fifo_rst_inst/gen_rst_ic.wrst_rd_inst
set_false_path -to [get_cells {syncstages_ff_reg[0]}]



####################################################################################
# Constraints from file : 'xpm_fifo_rst.tcl'
####################################################################################

# (c) Copyright 2023 Advanced Micro Devices, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of AMD and is protected under U.S. and international copyright
# and other intellectual property laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# AMD, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND AMD HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) AMD shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or AMD had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# AMD products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of AMD products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.
############################################################




# (c) Copyright 2023 Advanced Micro Devices, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of AMD and is protected under U.S. and international copyright
# and other intellectual property laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# AMD, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND AMD HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) AMD shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or AMD had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# AMD products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of AMD products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.
############################################################




# (c) Copyright 2023 Advanced Micro Devices, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of AMD and is protected under U.S. and international copyright
# and other intellectual property laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# AMD, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND AMD HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) AMD shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or AMD had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# AMD products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of AMD products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.
############################################################


current_instance -quiet
current_instance u_video/u_rx_bridge/u_metadata
set_max_delay -datapath_only -from [filter [all_fanout -from [get_ports -scoped_to_current_instance -no_traverse wr_clk] -flat -endpoints_only] IS_LEAF] -through [get_pins -of_obj [get_cells -hier * -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==drom}] -filter DIRECTION==OUT] 7.200


# (c) Copyright 2023 Advanced Micro Devices, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of AMD and is protected under U.S. and international copyright
# and other intellectual property laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# AMD, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND AMD HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) AMD shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or AMD had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# AMD products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of AMD products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.
############################################################


current_instance -quiet
current_instance u_video/u_tx_bridge/u_metadata
set_max_delay -datapath_only -from [filter [all_fanout -from [get_ports -scoped_to_current_instance -no_traverse wr_clk] -flat -endpoints_only] IS_LEAF] -through [get_pins -of_obj [get_cells -hier * -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==drom}] -filter DIRECTION==OUT] 6.667



# User Generated miscellaneous constraints 

current_instance -quiet
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CLKIN1_PERIOD 7.2 [get_cells u_clocks/u_rx_pll]

####################################################################################
# Constraints from file : 'external_io_candidate.xdc'
####################################################################################

# Conditional board envelope RX[-.30,+.45] TX[-.34,+.40] ns.
# RX PHY output setup/hold >=1.2ns, BUFIO follows actual duty.
# TX0 required clock-data window at PHY pins [1.0,2.6]ns.
create_generated_clock -name rgmii_tx_forward -source [get_pins u_io/u_tx/u_forward/C] -edges {2 4 6} [get_ports rgmii_txc]
set_input_delay -clock phy_rx125 -max 2.490 [get_ports {{rgmii_rxd[*]} rgmii_rxctl}]
set_input_delay -clock phy_rx125 -min -add_delay 0.900 [get_ports {{rgmii_rxd[*]} rgmii_rxctl}]
set_input_delay -clock phy_rx125 -clock_fall -max -add_delay 3.210 [get_ports {{rgmii_rxd[*]} rgmii_rxctl}]
set_input_delay -clock phy_rx125 -clock_fall -min -add_delay 0.900 [get_ports {{rgmii_rxd[*]} rgmii_rxctl}]
set_output_delay -clock rgmii_tx_forward -max 1.400 [get_ports {{rgmii_txd[*]} rgmii_txctl}]
set_output_delay -clock rgmii_tx_forward -min -add_delay -1.740 [get_ports {{rgmii_txd[*]} rgmii_txctl}]
set_output_delay -clock rgmii_tx_forward -clock_fall -max -add_delay 1.400 [get_ports {{rgmii_txd[*]} rgmii_txctl}]
set_output_delay -clock rgmii_tx_forward -clock_fall -min -add_delay -1.740 [get_ports {{rgmii_txd[*]} rgmii_txctl}]
set_load 12.000 [get_ports {{rgmii_txd[*]} rgmii_txctl rgmii_txc}]
set_property LOAD 12 [get_ports {rgmii_txd[3]}]
set_property LOAD 12 [get_ports {rgmii_txd[2]}]
set_property LOAD 12 [get_ports {rgmii_txd[1]}]
set_property LOAD 12 [get_ports {rgmii_txd[0]}]
set_property LOAD 12 [get_ports rgmii_txctl]
set_property LOAD 12 [get_ports rgmii_txc]
set_property SLEW FAST [get_ports {{rgmii_txd[*]} rgmii_txctl rgmii_txc}]
set_property DRIVE 8 [get_ports {{rgmii_txd[*]} rgmii_txctl}]
set_property DRIVE 12 [get_ports rgmii_txc]


# User Generated XDC timing constraints 

set_clock_uncertainty 0.100 [all_clocks]
set_clock_uncertainty -from [get_clocks phy_rx125] -to [get_clocks phy_rx125] 0.000
set_clock_uncertainty -from [get_clocks -of_objects [get_pins u_io/u_tx/u_forward/C]] -to [get_clocks rgmii_tx_forward] 0.000
create_generated_clock -name mdc_out -source [get_ports sys_clk50] -divide_by 500 [get_ports mdc]
set_output_delay -clock mdc_out -max 10.000 [get_ports mdio]
set_output_delay -clock mdc_out -min -10.000 [get_ports mdio]
set_false_path -from [get_ports mdio] -to [get_pins u_management/u_startup/u_mdio/mdio_meta_q_reg/D]
set_multicycle_path -setup -start -from [get_cells {u_management/u_startup/u_mdio/mdio_out_q_reg u_management/u_startup/u_mdio/mdio_oe_q_reg}] -to [get_ports mdio] 250
set_multicycle_path -hold -start -from [get_cells {u_management/u_startup/u_mdio/mdio_out_q_reg u_management/u_startup/u_mdio/mdio_oe_q_reg}] -to [get_ports mdio] 249
set_false_path -to [get_ports uart_tx]
set_false_path -through [get_pins {u_clocks/u_sys_mmcm/LOCKED u_clocks/u_rx_pll/LOCKED u_clocks/u_ref_mmcm/LOCKED}]
set_false_path -to [get_pins [list {rr_reg[0]/PRE} {rr_reg[1]/PRE} {tr_reg[0]/PRE} {tr_reg[1]/PRE} {u_video/u_rx_bridge/rd_reset_q_reg[0]/PRE} {u_video/u_rx_bridge/rd_reset_q_reg[1]/PRE}]]
set_false_path -to [get_pins [list {u_clocks/bad_sync_reg[0]/PRE} {u_clocks/bad_sync_reg[1]/PRE}]]
set_false_path -to [get_pins [list {u_io/u_tx/release_sync_reg[0]/PRE} {u_io/u_tx/release_sync_reg[1]/PRE}]]
set_false_path -through [get_pins u_clocks/u_delay_control/RDY] -to [get_pins {u_clocks/delay_ready_sync_reg[0]/D}]

# User Generated miscellaneous constraints 

create_waiver -type CDC -id {CDC-10} -user "ACX750_root" -desc "Terminal sticky single-bit PHY permission enters an async-assert two-stage reset synchronizer, then 1024 core cycles. The fault OR is not a data crossing. Stage D and all reset consumers remain timed." -tags "ACX750_PHY_TERMINAL_PERMISSION_FAULT" -from {u_clocks/delay_reset_count_reg[3]/C} -to {u_clocks/delay_reset_count_reg[3]/C} -timestamp "Fri Oct  9 12:01:32 GMT 2026"
create_waiver -type CDC -id {CDC-10} -user "ACX750_root" -desc "Source-bound registered IDELAYCTRL reset is an intentional asynchronous fault request, asserted for at least 64 stable ref200 edges. Release passes the verified zero-shift core reset synchronizer and 1024 cycles. Source D/CE, reference reset recovery/removal and all consumers remain timed." -tags "ACX750_REGISTERED_CALIBRATION_FAULT" -from {u_clocks/delay_reset_count_reg[3]/C} -to {u_clocks/delay_reset_count_reg[3]/C} -timestamp "Fri Oct  9 12:01:33 GMT 2026"

# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
