# INTERNAL EXPERIMENT: external DDR min/max omitted, cannot release BIT.
set_property PACKAGE_PIN W19 [get_ports {sys_clk50}]
set_property IOSTANDARD LVCMOS33 [get_ports {sys_clk50}]
set_property PACKAGE_PIN D21 [get_ports {reset_n}]
set_property IOSTANDARD LVCMOS33 [get_ports {reset_n}]
set_property PACKAGE_PIN Y18 [get_ports {rgmii_rxc}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxc}]
set_property PACKAGE_PIN T20 [get_ports {rgmii_rxctl}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxctl}]
set_property PACKAGE_PIN AB21 [get_ports {rgmii_txc}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txc}]
set_property PACKAGE_PIN AA19 [get_ports {rgmii_txctl}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txctl}]
set_property PACKAGE_PIN P14 [get_ports {phy_reset_n}]
set_property IOSTANDARD LVCMOS33 [get_ports {phy_reset_n}]
set_property PACKAGE_PIN P20 [get_ports {rgmii_rxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[0]}]
set_property PACKAGE_PIN N15 [get_ports {rgmii_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[1]}]
set_property PACKAGE_PIN AA18 [get_ports {rgmii_rxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[2]}]
set_property PACKAGE_PIN AB18 [get_ports {rgmii_rxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[3]}]
set_property PACKAGE_PIN AB20 [get_ports {rgmii_txd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[0]}]
set_property PACKAGE_PIN Y19 [get_ports {rgmii_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[1]}]
set_property PACKAGE_PIN AB22 [get_ports {rgmii_txd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[2]}]
set_property PACKAGE_PIN W20 [get_ports {rgmii_txd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[3]}]
set_property PACKAGE_PIN U22 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN V22 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN W21 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN W22 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN Y21 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN Y22 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN N13 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN N17 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
create_clock -name sys50 -period 20.0 [get_ports sys_clk50]
create_clock -name phy_rx125 -period 7.2 -waveform {0 3.24} [get_ports rgmii_rxc]
set_false_path -from [get_ports reset_n]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports mdc]
set_property -dict {PACKAGE_PIN U21 IOSTANDARD LVCMOS33} [get_ports mdio]
set_property -dict {PACKAGE_PIN M21 IOSTANDARD LVCMOS33} [get_ports uart_tx]
set_property -dict {SLEW SLOW DRIVE 4} [get_ports {mdc mdio}]
set_property PULLUP TRUE [get_ports mdio]
